server:
  port: 18888
  
spring:
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 1234
    driver-class-name:  org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2console
